### PR TITLE
Reorganize Notebooks

### PR DESCRIPTION
**Pull request by ttdu**
Currently, notebooks and markdown files share one folder. This PR separates them for clarity: one notebook folder, one markdown folder. Other changes:

- Each notebook lives in a folder. This is standard in other github repos, and isolates any "mess" created by a notebook: downloads, images, required files, etc
- Updated links so that they open the correct files.
- New list of "cloud optimized" tutorials

Qs for Octarine: Some notebooks live in "code": why? Can they be migrated as well.
BEFORE MERGING: Make sure to update introduction.md with feedback from "tike re-design". To be discussed during 8 Dec 23 meeting

### CODE REVIEW

**Comment by jaytmiller** [comment]
Personally I'm OK with moving the notebooks out of code to content.   However ATM we're in the process of partitioning our image repo and the test_notebooks are used for regression tests so now isn't a good time.  I could be wrong but one other consideration is that the test_notebooks,  while public,  aren't really intended to teach users,  they're more intended to define and prioritize and test desired packages for the Tess environment than be tutorials.

**Review by jaytmiller — APPROVED** [review]
Overall this looks great!   While I addressed some of your questions,  I don't think my answers imply changing this PR,  just things not to add yet.

With that said,  I did notice some notebooks changing from their configured Tess kernel back to the base Python kernel... which means they won't work unless a user explicitly selects Tess after opening but prior to running.  In some ways this is also intermingled with the git-sync system which leaves behind backup files because the CLI tool we used to run automatically to reconfigure notebooks for our environment goes nuts with notebook kernel fixes;  hence set-notebook-kernel is disabled.  Just wanted to explain the situation,  to get correct kernels you should develop on the TIKE platform or use the set-notebook-kernel tool or just edit the .ipynb JSON prior to committing.

Again,  nice work,  nice to see tike_content being improved again!

**Comment by ttdu** [comment]
Thanks for all the feedback!

I'll make sure I switch the kernel back, I ran the notebooks on my computer and forgot to change before committing.

**Comment by ttdu** [comment]
Ready for merge, pending approval of the new introduction:

**Please note!** Your home directory (/home/jovyan) is saved and will persist between sessions. In addition to being saved on AWS, your data is backed up twice a month; even so, it is always prudent to save important files in multiple locations. Please store large files sparingly, as we limit storage to 25GB and will remove excess data when necessary.

**Pull request merged**
