### PR TITLE
Proposal to update TIKE content

### PR DESCRIPTION
**Pull request by barentsen**
This PR documents a proposal to revamp the markdown content a TIKE user will see once their JupyterHub instance has been started.

## New introduction page

Most notably, this PR proposes a short-but-sweet introduction page (`Introduction.md`) which makes it easier to discover the key information a user needs to get started. This new introduction currently looks as follows:

Screen Shot 2021-06-16 at 8 16 20 AM

## Further work

I envisage further improvements (either via this PR or new ones) to include the following items:
* Adding documentation on the default Python environments (i.e. kernels) provided by TIKE.
* Adding tutorials specific to leveraging the TESS data available in S3.  In particular, documenting the use of `tesscut` in the cloud (cf. https://github.com/spacetelescope/astrocut/pull/44).
* Updating the list of pre-installed software packages (cf. `software-installed.md`).
* Reviewing the guidance we want to provide users on how long they may expect a server instance and/or data to persist (cf. caution message at the bottom of `Introduction.md`).
* Figuring out how to best integrate `tike_content` with the relevant TESS and Kepler science tutorials that we created last summer in `spacetelescope/notebooks`.  These notebooks do not currently appear to be pulled into TIKE.

### CODE REVIEW

**Comment by barentsen** [comment]
Note: this PR adds five SVG icons under `images/icons`.  These icons were copied from https://github.com/google/material-design-icons under the Apache License 2.0.  I included a file called `images/icons/LICENSE` to document this.

**Comment by jaytmiller** [comment]
This is awesome!   One comment:  spacetelescope/notebooks is checked out as spacetelescope-notebooks in the Tike docker image.   I don't recall my rationale for the name change,   possibly just the opinion that "notebooks" is too general,  I'll submit a PR to change it to "notebooks".

**Comment by barentsen** [comment]
@jaytmiller Ooops, my bad, I simply didn't spot `spacetelescope-notebooks` in the home directory!  I think keeping the name is fine; calling it `notebooks` does risk being too generic/vague.

I will go ahead and modify this PR to have `tike_content` take advantage of the local presence of `spacetelescope-notebooks`.

**Comment by jaytmiller** [comment]
Really nice work!

**Pull request merged**
