### PR TITLE
demo of TIKE speedup for TESS cutouts

### PR DESCRIPTION
**Pull request by ttdu**
Adding a new NB that takes users through 3 methods of generating cutouts. Makes use of TIKE for huge speedup compared to using a local machine

### CODE REVIEW

**Comment by gsnyder206** [comment]
Trying this notebook in TIKE, I get an error "no module named multi" at cell [1]. Omitting that line from cell 1 moves the error to cell [15] when doing the multiprocessing.

**Comment by ttdu** [comment]
Good catch, Greg. The NB needs three files, so it'll have to live within its own folder. 

I'd actually like _all_ notebooks to follow this folder structure to be consistent with the ST repository. An added benefit is that downloads don't clutter the list of available notebooks. This will be a separate PR.

**Comment by gsnyder206** [comment]
Note that there is already a notebook named "tesscut-in-the-cloud.ipynb".  I'd recommend choosing a different filename and directory name to avoid confusion.

**Comment by jaytmiller** [comment]
This seems to run great now,  nice!   

I only have a few related questions for Greg:   
1. is "content" the right directory to put the  new notebook folder in?  it looks odd with all the markdown and when other notebooks are in "code".  
2. does putting something in "content" have any magical consequences like potentially appearing in some way on the splash page?

**Comment by gsnyder206** [comment]
1. I think "content" is fine for this notebook, though "code" would work, too.
2. There are no magical consequences.  You'd have to modify the splash page in order to have the notebook appear there.

**Comment by jaytmiller** [comment]
OK,  I know I'm coming in late but it looks great to me,   I think we should merge.

**Comment by ttdu** [comment]
Following some last-minute feedback from a team member, I agree: ready for merger.

**Comment by jaytmiller** [comment]
Nice notebook,  thanks!

**Pull request merged**
