### PR TITLE
Adding LCViz tutorial notebook

### PR DESCRIPTION
**Pull request by rosteen**
Basic example of using LCViz with data retrieval from S3. Apparently the data retrieval, which works locally for me, doesn't actually work on TIKE, so this will need a little debugging.

### CODE REVIEW

**Comment by ttdu** [comment]
after running .flatten in the code cell, the plot looks strange: 
flatten

bizarrely, if I open the "flatten" option in the side menu, the points re-appear:
working-flatten

**Comment by kecnry** [comment]
This is a known bug that we are trying to get fixed upstream in bqplot.  If we can't get that in in time, perhaps we should disable normalization in the notebook?

**Comment by rosteen** [comment]
As Kyle said, this is an upstream bug that I'm hoping gets resolved in the next week or two (i.e., before this notebook would be merged). I should have mentioned it when I opened this PR - if for some reason it's not fixed by the end of November I'll remove that section.

**Comment by rosteen** [comment]
I added a note about the display bug and an edit to avoid it (by not normalizing the flattened curve), as well as one fix that I think was needed due to the new Astropy release.

**Comment by ttdu** [comment]
last thing and then I'll merge: if we're using a literature reference, we should cite it. It's not clear to be which of the [three papers on HAT-P-11 authored by Brett in 2017](https://ui.adsabs.harvard.edu/search/fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=(database%3Aastronomy%20OR%20database%3Aphysics)&q=%20%20first_author%3A%22Morris%22%20%20year%3A2017%20%20full%3A%22HAT-P-11%22&sort=date%20desc%2C%20bibcode%20desc&p_=0) is the correct one

**Comment by kecnry** [comment]
@bmorris3 - any preference?

**Comment by rosteen** [comment]
FYI the upstream bug with displaying the flattened light curve was fixed, so I removed the workaround.

**Pull request merged**
